// #region rayfin:app-owned — copied verbatim by the Rayfin CLI; edit freely.
//-----------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
//        Copyright (c) Microsoft Corporation.  All rights reserved.
//        Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

import type {
  ConnectorConfig,
  ConnectorsRuntime,
} from '@microsoft/rayfin-connectors';
// #endregion rayfin:app-owned

// @generated by `rayfin connector add` — do not edit below this line.
//
// Regenerated from rayfin.yml on every `rayfin connector add` and
// `rayfin connector remove`. To take ownership of this file, delete the
// line above; the CLI will then print the required wiring instead of
// rewriting it.


export type AppConnectorsSchema = Record<string, never>;

export const connectorConfigs: Record<string, ConnectorConfig> = {};

export const connectorRuntimes: ConnectorsRuntime = {};
